apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: habebabakr4789/finalproject-appointment-service:latest
        imagePullPolicy:  Always 
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: PATIENT_SERVICE_URL
          value: "http://patient-service.healthcare.svc.cluster.local:3000"
        - name: EHR_SERVICE_URL
          value: "http://ehr-service.healthcare.svc.cluster.local:3001"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthcare
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002