version: '3.8'

services:
  appointment-service:
    build: "./project_back/Appointment Scheduling Service"
    ports: ["3002:3002"]
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PATIENT_SERVICE_URL: ${PATIENT_SERVICE_URL}
      EHR_SERVICE_URL: ${EHR_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

  patient-service:
    build: ./project_back/PatientService
    ports: ["3000:3000"] 
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}

  ehr-service:
    build: ./project_back/EHR_Service
    ports: ["3001:3001"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build:
      context: "./front"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - appointment-service
      - patient-service
      - ehr-service
