apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-service
  template:
    metadata:
      labels:
        app: ehr-service
    spec:
      containers:
      - name: ehr-service
        image: habebabakr4789/finalproject-ehr-service:latest
        imagePullPolicy:  Always 
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "cluster0.muorswj.mongodb.net"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: DB_NAME
          value: "healthcare_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ehr-service
  namespace: healthcare
spec:
  type: NodePort
  selector:
    app: ehr-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001